import * as fs from 'fs';
import * as path from 'path';
import {
  AttachPolicyCommand,
  AttachThingPrincipalCommand,
  CreateKeysAndCertificateCommand,
  CreatePolicyCommand,
  CreateThingCommand,
  DescribeEndpointCommand,
  IoTClient,
  ListPoliciesCommand,
  ListThingsCommand,
} from '@aws-sdk/client-iot';

type CliArgs = {
  deviceId: string;
  stage: string;
  region: string;
  outputDir: string;
  esp32SecretsDir: string;
};

const APP_TAG = { Key: 'app', Value: 'irrigation-system' };

const readArg = (name: string): string | undefined => {
  const prefix = `--${name}=`;
  const match = process.argv.find((arg) => arg.startsWith(prefix));
  return match ? match.slice(prefix.length) : undefined;
};

const getArgs = (): CliArgs => {
  const deviceId = readArg('device-id') ?? process.env.DEVICE_ID;
  const stage = readArg('stage') ?? process.env.STAGE ?? 'dev';
  const region = readArg('region') ?? process.env.AWS_REGION ?? 'eu-central-1';
  const outputDir = readArg('output-dir') ?? path.join(process.cwd(), 'output', 'devices', deviceId ?? 'unknown');
  const esp32SecretsDir =
    readArg('esp32-secrets-dir') ??
    path.resolve(process.cwd(), '..', 'irrigation-system-esp32', 'secrets');

  if (!deviceId) throw new Error('Missing device id. Use --device-id=<thingName>.');

  return { deviceId, stage, region, outputDir, esp32SecretsDir };
};

const policyNameForStage = (stage: string): string => `irrigation-device-policy-${stage}`;

const buildPolicyDocument = (region: string, accountId: string): string =>
  JSON.stringify({
    Version: '2012-10-17',
    Statement: [
      {
        Effect: 'Allow',
        Action: ['iot:Connect'],
        Resource: [`arn:aws:iot:${region}:${accountId}:client/\${iot:Connection.Thing.ThingName}`],
      },
      {
        Effect: 'Allow',
        Action: ['iot:Publish', 'iot:Receive'],
        Resource: [
          `arn:aws:iot:${region}:${accountId}:topic/$aws/things/\${iot:Connection.Thing.ThingName}/shadow/*`,
          `arn:aws:iot:${region}:${accountId}:topic/irrigation/devices/\${iot:Connection.Thing.ThingName}/*`,
        ],
      },
      {
        Effect: 'Allow',
        Action: ['iot:Subscribe'],
        Resource: [
          `arn:aws:iot:${region}:${accountId}:topicfilter/$aws/things/\${iot:Connection.Thing.ThingName}/shadow/*`,
        ],
      },
      {
        Effect: 'Allow',
        Action: ['iot:GetThingShadow', 'iot:UpdateThingShadow'],
        Resource: [`arn:aws:iot:${region}:${accountId}:thing/\${iot:Connection.Thing.ThingName}`],
      },
    ],
  });

const writeEsp32SecretsHeader = (
  targetDir: string,
  deviceId: string,
  endpoint: string,
  certificatePem: string,
  privateKeyPem: string,
): void => {
  fs.mkdirSync(targetDir, { recursive: true });
  const headerPath = path.join(targetDir, 'iot_secrets.h');

  const content = `#pragma once

// Generated by irrigation-system-aws/scripts/provision-device.ts
// Do not commit this file.

static const char IOT_THING_NAME[] = "${deviceId}";
static const char IOT_ENDPOINT[] = "${endpoint}";

static const char IOT_DEVICE_CERT[] = R"CERT(
${certificatePem.trim()}
)CERT";

static const char IOT_DEVICE_PRIVATE_KEY[] = R"KEY(
${privateKeyPem.trim()}
)KEY";
`;

  fs.writeFileSync(headerPath, content, 'utf8');
};

const ensurePolicy = async (
  iot: IoTClient,
  stage: string,
  region: string,
  accountId: string,
): Promise<string> => {
  const policyName = policyNameForStage(stage);
  const existing = await iot.send(new ListPoliciesCommand({ pageSize: 250 }));
  const found = existing.policies?.find((policy) => policy.policyName === policyName);
  if (found?.policyArn) return policyName;

  await iot.send(
    new CreatePolicyCommand({
      policyName,
      policyDocument: buildPolicyDocument(region, accountId),
      tags: [APP_TAG, { Key: 'stage', Value: stage }],
    }),
  );

  return policyName;
};

const ensureThing = async (iot: IoTClient, deviceId: string, stage: string): Promise<void> => {
  const existing = await iot.send(new ListThingsCommand({ maxResults: 250 }));
  const found = existing.things?.some((thing) => thing.thingName === deviceId);
  if (found) return;

  await iot.send(
    new CreateThingCommand({
      thingName: deviceId,
      attributePayload: {
        attributes: {
          app: 'irrigation-system',
          stage,
        },
      },
    }),
  );
};

const main = async (): Promise<void> => {
  const args = getArgs();
  const iot = new IoTClient({ region: args.region });
  const { STSClient, GetCallerIdentityCommand } = await import('@aws-sdk/client-sts');
  const sts = new STSClient({ region: args.region });
  const identity = await sts.send(new GetCallerIdentityCommand({}));
  const accountId = identity.Account;
  if (!accountId) throw new Error('Unable to resolve AWS account id.');

  await ensurePolicy(iot, args.stage, args.region, accountId);
  await ensureThing(iot, args.deviceId, args.stage);

  const cert = await iot.send(new CreateKeysAndCertificateCommand({ setAsActive: true }));
  if (!cert.certificateArn || !cert.certificatePem || !cert.keyPair?.PrivateKey || !cert.certificateId) {
    throw new Error('Failed to create device certificate.');
  }

  const policyName = policyNameForStage(args.stage);
  await iot.send(new AttachPolicyCommand({ policyName, target: cert.certificateArn }));
  await iot.send(
    new AttachThingPrincipalCommand({
      thingName: args.deviceId,
      principal: cert.certificateArn,
    }),
  );

  const endpoint = await iot.send(new DescribeEndpointCommand({ endpointType: 'iot:Data-ATS' }));
  if (!endpoint.endpointAddress) throw new Error('Unable to resolve IoT endpoint.');

  fs.mkdirSync(args.outputDir, { recursive: true });
  fs.writeFileSync(path.join(args.outputDir, 'AmazonRootCA1.pem'), fs.readFileSync(path.join(__dirname, 'AmazonRootCA1.pem')));
  fs.writeFileSync(path.join(args.outputDir, 'device.pem.crt'), cert.certificatePem, 'utf8');
  fs.writeFileSync(path.join(args.outputDir, 'private.pem.key'), cert.keyPair.PrivateKey, 'utf8');
  fs.writeFileSync(
    path.join(args.outputDir, 'provisioning.json'),
    JSON.stringify(
      {
        deviceId: args.deviceId,
        stage: args.stage,
        region: args.region,
        endpoint: endpoint.endpointAddress,
        certificateId: cert.certificateId,
        certificateArn: cert.certificateArn,
        policyName,
        tags: { app: 'irrigation-system', stage: args.stage },
      },
      null,
      2,
    ),
    'utf8',
  );

  writeEsp32SecretsHeader(
    args.esp32SecretsDir,
    args.deviceId,
    endpoint.endpointAddress,
    cert.certificatePem,
    cert.keyPair.PrivateKey,
  );

  console.log(
    JSON.stringify(
      {
        ok: true,
        deviceId: args.deviceId,
        endpoint: endpoint.endpointAddress,
        outputDir: args.outputDir,
        esp32SecretsHeader: path.join(args.esp32SecretsDir, 'iot_secrets.h'),
        nextSteps: [
          `npm run seed:access -- --table=device_user_access_${args.stage} --user-sub=<cognito-sub> --device-id=${args.deviceId}`,
          'Flash ESP32 firmware with generated secrets/iot_secrets.h',
        ],
      },
      null,
      2,
    ),
  );
};

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : 'Unknown error';
  console.error(JSON.stringify({ ok: false, error: message }, null, 2));
  process.exit(1);
});
